# Generated by Django 5.1.7 on 2025-03-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Noname', max_length=255, verbose_name='Название')),
                ('img', models.ImageField(upload_to='', verbose_name='Фото')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('like', models.PositiveIntegerField(default=0, verbose_name='Лайки')),
            ],
            options={
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
