# Generated by Django 5.1.7 on 2025-03-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='what',
            field=models.PositiveIntegerField(default=0, verbose_name='вещи'),
        ),
    ]
