# Generated by Django 5.1.7 on 2025-03-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hz', '0002_photo_what'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='what',
            field=models.CharField(default='Noname', max_length=255, verbose_name='вещи'),
        ),
    ]
