# Generated by Django 5.1.7 on 2025-03-15 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hz', '0003_alter_photo_what'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={},
        ),
    ]
